"""
报告导出接口
支持 PDF、JSON、Markdown 格式
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse, PlainTextResponse
from loguru import logger
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from services.database import get_db
from models import Task

router = APIRouter(prefix="/api/export", tags=["导出"])


@router.get("/{task_id}/json")
async def export_json(task_id: str):
    """导出 JSON 格式报告"""
    db = next(get_db())
    try:
        task = db.query(Task).filter(Task.task_id == task_id).first()
        
        if not task:
            raise HTTPException(status_code=404, detail="任务不存在")
        
        if task.status != 'completed':
            raise HTTPException(status_code=400, detail="任务未完成")
        
        report_data = {
            'task_id': task.task_id,
            'filename': task.filename,
            'duration': task.duration,
            'transcription': task.transcription,
            'analysis': task.analysis_result,
            'created_at': task.created_at.isoformat() if task.created_at else None
        }
        
        return JSONResponse(content=report_data)
    
    finally:
        db.close()


@router.get("/{task_id}/markdown")
async def export_markdown(task_id: str):
    """导出 Markdown 格式报告"""
    db = next(get_db())
    try:
        task = db.query(Task).filter(Task.task_id == task_id).first()
        
        if not task:
            raise HTTPException(status_code=404, detail="任务不存在")
        
        if task.status != 'completed':
            raise HTTPException(status_code=400, detail="任务未完成")
        
        # 生成 Markdown 报告
        md_content = f"""# 直播复盘报告

**文件名**: {task.filename}  
**时长**: {task.duration:.1f}秒  
**分析时间**: {task.created_at.strftime('%Y-%m-%d %H:%M') if task.created_at else 'N/A'}

---

## 转写文字

{task.transcription[:5000] if task.transcription else '无'}

---

## 话术分析

{task.analysis_result.get('speaking_techniques', []) if task.analysis_result else '无'}

---

## 归因分析

{task.analysis_result.get('attribution_analysis', []) if task.analysis_result else '无'}

---

## 改进建议

{task.analysis_result.get('suggestions', []) if task.analysis_result else '无'}

---

*Generated by LiveMirror*
"""
        
        return PlainTextResponse(content=md_content, media_type="text/markdown")
    
    finally:
        db.close()


@router.get("/{task_id}/pdf")
async def export_pdf(task_id: str):
    """导出 PDF 格式报告"""
    # TODO: 使用 ReportLab 或 WeasyPrint 生成 PDF
    # 暂时返回 Markdown 格式
    return await export_markdown(task_id)
